name: Reddit News Aggregator

env:
  HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

on:
  schedule:
  - cron: '0 7 * * *' # Every day at 7 AM UTC
  workflow_dispatch:
    # Allows manual runs

jobs:
  newsbot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Get dependencies
      run: go mod tidy

    - name: Build
      run: go build -v .

    - name: Run Bot
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
      run: ./reddit-news-aggregator
